config/routes.rb
Bugpromo::Application.routes.draw do
  root 'sheets#index'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users, :only => [:new, :create]
  resources :sheets do
    resources :tbl_specs, :only => [:index]
    resources :ae_specs, only: [:index]
  end
  resources :tbl_specs, only: [:index]
  resources :ae_specs, only: [:index]
  resources :properties, :only => [:index, :create, :destroy, :update]
  resources :teamnames, :only => [:index, :create, :destroy, :update]
  

end

app/models/ae_spec.rb
class AeSpec < ActiveRecord::Base
	belongs_to :sheet
end

app/models/airtime.rb
class Airtime < ActiveRecord::Base
	belongs_to :sheet
end

app/models/promo.rb
class Promo < ActiveRecord::Base
	belongs_to :sheet
	has_one :ae_spec, dependent: :delete
end

app/models/property.rb
class Property < ActiveRecord::Base
	has_many :sheets
  has_many :tbl_specs, through: :sheets
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
	belongs_to :user
	belongs_to :property
	has_many :promos, dependent: :delete_all
	has_many :airtimes
	has_many :ae_specs, dependent: :delete_all
	has_many :tbl_specs, dependent: :delete_all

	accepts_nested_attributes_for :airtimes
	accepts_nested_attributes_for :promos

  validates_presence_of :weekday1, :team1, :team2, :property_name
  validate :check_first_time

  def check_first_time
    if airtimes[0].timezone == "" || airtimes[0].time == nil
      errors.add(:id,"First airtime must be filled out and in the ET timezone")
      false
    end
  end
end

app/models/tbl_spec.rb
class TblSpec < ActiveRecord::Base
	belongs_to :sheet

	def self.to_csv
    CSV.generate do |csv|
      csv << column_names[4..-1]
      all.each do |sheet|
        csv << sheet.attributes.values_at(*column_names[4..-1])
      end
    end
  end
end

app/models/teamname.rb
class Teamname < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :sheets

  validates_presence_of :name, on: :create
  validates_presence_of :email, on: :create
end

app/controllers/ae_specs_controller.rb
class AeSpecsController < ApplicationController
  def index
    if params[:sheet_id] then
      @ae_specs = AeSpec.where(sheet_id: params[:sheet_id])
    else
      @ae_specs = AeSpec.all.order(:id)
    end
    content = ""
    @ae_specs.each do |ae_spec|
      content += '"teamA = ["' + ae_spec.team1 + '"]'
      content += "</br>"
      content += 'teamB = ["' + ae_spec.team2 + '"]'
      content += "</br>"
      content += 'day = ["' + ae_spec.day + '"]'
      content += "</br>"
      content += 'start = ["' + ae_spec.start + '"]"'
      content += "</br>"
      content += "</br>"
    end
    respond_to do |format|
      format.html { render text: content }
    end
  end
end

app/controllers/airtimes_controller.rb
class AirtimesController < ApplicationController
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
	def index
		@sheets = Sheet.all
	end

	def new
		@sheet = current_user.sheets.build
		3.times {@sheet.airtimes.build}
		5.times {@sheet.promos.build}
		@property_names = Property.all.map{|x| x.name}
		@teamnames = Teamname.all.map{|x| x.name}
	end

	def create
		@sheet = current_user.sheets.build(sheet_params)
		@sheet.team1.upcase!
		@sheet.team2.upcase!
		@sheet.property_name.upcase!
		@property = Property.find_or_create_by(name: @sheet.property_name)
		if @sheet.save
			update_property(@property)
			update_teamnames

			update_tbl_spec(@sheet.weekday1, @property)
			update_tbl_spec(@sheet.weekday2, @property)
			update_tbl_spec(@sheet.weekday3, @property)

			update_ae_spec(@sheet.weekday1)
			update_ae_spec(@sheet.weekday2)	
			update_ae_spec(@sheet.weekday3)	

			redirect_to sheets_path
		else
			render :new
		end
	end

	def update_tbl_spec(weekday, property)
		if !weekday.empty?
			#CREATE TBL SPEC  --- CSV FILE
			@tbl_spec = TblSpec.find_or_create_by(sheet_id: @sheet.id, day: weekday)
			@tbl_spec.sheet_id = @sheet.id
			@tbl_spec.day = weekday
			@tbl_spec.image_path = property.image_path
			@tbl_spec.property_name = @sheet.property_name
			@tbl_spec.team1 = @sheet.team1
			@tbl_spec.team2 = @sheet.team2
			@tbl_spec.time_variable = ""
			@sheet.airtimes.each_with_index do |airtime, i|
				if airtime.time
					@tbl_spec.time_variable += airtime.time.hour.to_s + ":" + sprintf('%02d',airtime.time.min) + " " + airtime.timezone
					@tbl_spec.time_variable += " / " unless @sheet.airtimes[i+1].time == nil
				end
			end
			@tbl_spec.world = @sheet.world
			@tbl_spec.east = @sheet.east
			@tbl_spec.ontario = @sheet.ontario
			@tbl_spec.west = @sheet.west
			@tbl_spec.pacific = @sheet.pacific
			@tbl_spec.one = @sheet.one
			@tbl_spec.logo_path = property.logo_path
			@tbl_spec.save 
		end
	end

	def update_ae_spec(weekday)
		airtime = @sheet.airtimes.select{|a| a[:timezone] == "ET" }.first
		if airtime && !weekday.empty? 
			#CREATE AE SPEC  --- TEXT FILE FOR AFTEREFFECTS
			@ae_spec = AeSpec.find_or_create_by(sheet_id: @sheet.id, day: weekday)
			@ae_spec.team1 = @sheet.team1
			@ae_spec.team2 = @sheet.team2
			@ae_spec.day = weekday
			@ae_spec.start = airtime[:time].hour
			@ae_spec.sheet_id = @sheet.id
			@ae_spec.save
		end
	end

	def update_property(property)
		#ADDS NEW ENTRY TO PROPERTY TABLE IF NAME DOES NOT EXIST
		property.save
		@sheet.property_id = property.id
	end

	def update_teamnames
				#ADDS TEAMNAMES TO TEAMNAME TABLE IF NAMES DO NOT EXIST
		@teamname1 = Teamname.find_or_create_by(name: @sheet.team1)
		@teamname1.save

		@teamname2 = Teamname.find_or_create_by(name: @sheet.team2)
		@teamname2.save
	end

	def edit
		@sheet = Sheet.find(params[:id])
		@property_names = Property.all.map{|x| x.name}
		@teamnames = Teamname.all.map{|x| x.name}
	end

	def update
		@sheet = Sheet.find(params[:id])
		@sheet.team1.upcase!
		@sheet.team2.upcase!
		@sheet.property_name.upcase!

		@property = Property.find_or_create_by(name: @sheet.property_name)
		update_property(@property)
		update_teamnames

		update_tbl_spec(@sheet.weekday1, @property)
		update_tbl_spec(@sheet.weekday2, @property)
		update_tbl_spec(@sheet.weekday3, @property)

		update_ae_spec(@sheet.weekday1)
		update_ae_spec(@sheet.weekday2)	
		update_ae_spec(@sheet.weekday3)

		if @sheet.update_attributes(sheet_params)
			redirect_to edit_sheet_path(@sheet)
		else
			render :edit
		end
	end

	def show
		@sheet = Sheet.find(params[:id])
		redirect_to edit_sheet_path(@sheet)
	end

	def destroy
		@sheet = Sheet.find(params[:id])
		@sheet.destroy
		redirect_to sheets_path
	end

	def sheet_params
		params.require(:sheet).permit(:weekday1,:weekday2,:weekday3,:sens,:flames,:oilers,:van_hky,:world,:one,:east,:ontario,:west,:pacific,:is_360,:snipe_required,:team1,:team2,:property_name,:property_id,:user_id,:note,:event_date,:due_date, airtimes_attributes: [:id,:sheet_id,:timezone,:time], promos_attributes: [:id,:length,:quantel_name,:s4m_name,:mcr_number,:purge_date,:sheet_id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to sheets_path
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
  

end

app/helpers/ae_specs_helper.rb
module AeSpecsHelper
end

app/helpers/airtimes_helper.rb
module AirtimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/helpers/tbl_specs_helper.rb
module TblSpecsHelper
end

app/helpers/teamnames_helper.rb
module TeamnamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ae_specs/index.html.erb
<div id="ae_spec_box">
  <%= @content %>
</div>

app/views/sheets/_sheetform.html.erb
<%= form_for @sheet do |s| %>

  <% if @sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sheet.errors.count, "error") %> prevented this sheet from being saved.</h2>
      <ul>
      <% @sheet.errors.full_messages.each do |msg| %>
        <%= msg %>. 
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="form_container">
    <table id = "checkbox_container">
      <tr class = "checkbox">
        <td class = "checkbox_label field_name">SENS</td>
        <td class = "checkbox_box"><%= s.check_box :sens%></td>
      </tr>

      <tr class = "checkbox">
        <td class = "checkbox_label field_name">FLAMES</td>
        <td class = "checkbox_box"><%= s.check_box :flames%></td>
      </tr>

      <tr class = "checkbox">
        <td class = "checkbox_label field_name">OILERS</td>
        <td class = "checkbox_box"><%= s.check_box :oilers%></td>
      </tr>

      <tr class = "checkbox">
        <td class = "checkbox_label field_name">VAN HKY</td>
        <td class = "checkbox_box"><%= s.check_box :van_hky%></td>
      </tr>

      <tr class = "checkbox">
        <td class = "checkbox_label field_name">WORLD</td>
        <td class = "checkbox_box"><%= s.check_box :world%></td>
      </tr>

      <tr class = "checkbox">
        <td class = "checkbox_label field_name">ONE</td>
        <td class = "checkbox_box"><%= s.check_box :one%></td>
      </tr>

      <tr class = "checkbox">
        <td class = "checkbox_label field_name">EAST</td>
        <td class = "checkbox_box"><%= s.check_box :east%></td>
      </tr>

      <tr class = "checkbox">
        <td class = "checkbox_label field_name">ONTARIO</td>
        <td class = "checkbox_box"><%= s.check_box :ontario%></td>
      </tr>

      <tr class = "checkbox">
        <td class = "checkbox_label field_name">WEST</td>
        <td class = "checkbox_box"><%= s.check_box :west%></td>
      </tr>

      <tr class = "checkbox">
        <td class = "checkbox_label field_name">PACIFIC</td>
        <td class = "checkbox_box"><%= s.check_box :pacific%></td>
      </tr>

      <tr class = "checkbox">
        <td class = "checkbox_label field_name">360</td>
        <td class = "checkbox_box"><%= s.check_box :is_360%></td>
      </tr>

      <tr class = "checkbox">
        <td class = "checkbox_label field_name">SNIPE?</td>
        <td class = "checkbox_box"><%= s.check_box :snipe_required%></td>
      </tr>
    </table>

    <div id = "noncheck_container">
      <div id = "above_table">
        <div class = "property">
          <div class = "field_name">PROPERTY</div>
          <div class = "entry_area"><%= s.text_field :property_name, autocomplete: "off" %></div>
        </div>

        <div class = "teamname">
          <div class="field_name">TEAM 1</div>
          <div class="entry_area"><%= s.text_field :team1, autocomplete: "off" %></div>
          <div class="field_name">TEAM 2</div>
          <div class="entry_area"><%= s.text_field :team2, autocomplete: "off" %></div>
        </div>


        <div id = "weekdayboxes">
          <div class = "field_name">WEEKDAYS</div>
          <div class = "entry_area">
            <%= s.select :weekday1, options_for_select(["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY","TODAY","TONIGHT","TOMORROW"], @sheet.weekday1), {include_blank: true} %>
          </div>
          <div class = "entry_area">
            <%= s.select :weekday2, options_for_select(["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY","TODAY","TONIGHT","TOMORROW"], @sheet.weekday2), {include_blank: true} %>
          </div>
          <div class = "entry_area">
            <%= s.select :weekday3, options_for_select(["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY","TODAY","TONIGHT","TOMORROW"], @sheet.weekday3), {include_blank: true} %>
          </div>
        </div>

        <div id = "airtimes">
          <div class="field_name">AIRTIMES</div>
          <%= s.fields_for :airtimes do |airtime_form| %>
              <div class = "airtime_entry_area entry_area"><%=airtime_form.time_field :time %></div>
              <div class = "timezone_entry_area entry_area">
                <%=airtime_form.select :timezone, options_for_select(["ET","MT","PT"], @sheet.airtimes[airtime_form.index].timezone), {include_blank: true}%>
              </div>
          <% end %>
        </div>


        <div class = "datefield">
          <div class="field_name">EVENT DATE</div>
          <div class="entry_area"><%= s.date_field :event_date %></div>
          <div class="field_name">DUE DATE</div>
          <div class="entry_area"><%= s.date_field :due_date %></div>
        </div>

        <div class = "notefield">
          <div class="field_name">NOTE</div>
          <div class="entry_area"><%= s.text_field :note %></div>
        </div>
      </div>

      <div id = "promorowcontainer">
        <!--ROW SECTION-->
        <table>
          <tr>
            <td class="field_name length_column">Length</td>
            <td class="field_name quantel_column">Quantel Name</td>
            <td class="field_name s4m_column">S4M Name</td>
            <td class="field_name mcr_column">MCR #</td>
            <td class="field_name purge_column">Purge Date</td>
          </tr>
          <%= s.fields_for :promos do |promo_form| %>
            <tr>
              <td class="entry_area length_column">
                <%#=promo_form.label :length%>
                <%=promo_form.text_field :length%>
              </td>
              <td class="entry_area quantel_column">
                <%#=promo_form.label :quantel_name%>
                <%=promo_form.text_field :quantel_name%>
              </td>
              <td class="entry_area s4m_column">
                <%#=promo_form.label :s4m_name%>
                <%=promo_form.text_field :s4m_name%>
              </td>
              <td class="entry_area mcr_column">
                <%#=promo_form.label :mcr_number%>
                <%=promo_form.text_field :mcr_number%>
              </td>
              <td class="entry_area purge_column">
                <%#=promo_form.label :purge_date%>
                <%=promo_form.date_field :purge_date%>
              </td>
            </tr>
          <% end %>
        </table>
        <div id = "form_bottom">
          <% if current_user %>
            <%= s.submit %>
            <button>
              <%= link_to "Cancel", sheets_path %>
            </button>
          <% else %>
            <button>
              <%= link_to "Back", sheets_path %>
            </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>


<% if @property_names %>
  <script>
    $( "#sheet_property_name" ).autocomplete({source: <%= raw @property_names%>});
  </script>
<% end %>

<% if @teamnames %>
  <script>
    $( "#sheet_team1").autocomplete({source: <%= raw @teamnames%>});
    $( "#sheet_team2").autocomplete({source: <%= raw @teamnames%>});
  </script>
<% end %>

app/views/sheets/edit.html.erb
 <%= render partial: "sheetform"%>

app/views/sheets/index.html.erb
<table class="listtable">
	<tr>
		<td class="index_button">
			<%= link_to "View All-Sheet CSV", tbl_specs_path(format: "html") %>
		</td>
		<td class="index_button">
			<%= link_to "Download All-Sheet CSV", tbl_specs_path(format: "csv") %>
		</td>
		<td class="index_button">
			<%= link_to "View All-Sheet AE Format", ae_specs_path(format: "html") %>
		</td>
	</tr>
	<% @sheets.each do |sheet| %>
		<tr>
			<td class="field_name index_field">
				<%= link_to "DUE #{sheet.due_date} - #{sheet.team1} vs #{sheet.team2}, Creator: #{sheet.user.name}", sheet_path(sheet) %>
			</td>
			<% if sheet.tbl_specs %>
				<td class="index_button">
					<%= link_to "View CSV", sheet_tbl_specs_path(sheet.id, format:"html") %>
				</td>
				<td class="index_button">
					<%= link_to "Download CSV", sheet_tbl_specs_path(sheet.id, format:"csv") %>
				</td>
			<% end %>
			<% if sheet.ae_specs %>
				<td class="index_button">
					<%= link_to "View AE Format", sheet_ae_specs_path(sheet.id, format:"html")%>
				</td>
			<% end %>
			<% if current_user == sheet.user %>
				<td class="delete_button">
					<%= link_to "Delete Sheet", sheet_path(sheet.id), confirm: "Are you sure you wish to delete this sheet?", method: :delete %>
				</td>
			<% end %>
		</tr>
	<% end %>
</table>

app/views/sheets/new.html.erb
 <%= render partial: "sheetform"%>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "signuparea">
      <h1>Create New Account</h1>
      <div class = "field_name">EMAIL</div>
      <div class = "entry_area"><%=f.text_field :email %></div>
      <div class = "field_name">NICKNAME</div>
      <div class = "entry_area"><%=f.text_field :name %></div>
      <div class = "field_name">PASSWORD</div>
      <div class = "entry_area"><%=f.password_field :password %></div>
      <div class = "field_name">CONFIRM PASSWORD</div>
      <div class = "entry_area"><%=f.password_field :password_confirmation %></div>
      <div class = "signupbutton"><%= f.submit %></div>
  </div>
<% end %>
 