config/routes.rb
Bugpromo::Application.routes.draw do
  root 'sheets#index'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users, :only => [:new, :create]
  resources :sheets do
    resources :tbl_specs, :only => [:index]
    resources :ae_specs, only: [:index]
  end
  resources :tbl_specs, only: [:index]
  resources :ae_specs, only: [:index]
  resources :properties, :only => [:index, :create, :destroy, :update]
  resources :teamnames, :only => [:index, :create, :destroy, :update]
  

end

app/models/ae_spec.rb
class AeSpec < ActiveRecord::Base
	belongs_to :sheet
end

app/models/airtime.rb
class Airtime < ActiveRecord::Base
	belongs_to :sheet
end

app/models/promo.rb
class Promo < ActiveRecord::Base
	belongs_to :sheet
	has_one :ae_spec, dependent: :delete
end

app/models/property.rb
class Property < ActiveRecord::Base
	has_many :sheets
  has_many :tbl_specs, through: :sheets
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
	belongs_to :user
	belongs_to :property
	has_many :promos, dependent: :delete_all
	has_many :airtimes
	has_many :ae_specs, dependent: :delete_all
	has_many :tbl_specs, dependent: :delete_all

	accepts_nested_attributes_for :airtimes
	accepts_nested_attributes_for :promos

  validates_presence_of :weekday1, :team1, :team2, :property_name
  validate :check_first_time

  def check_first_time
    if airtimes[0].timezone == "" || airtimes[0].time == nil
      errors.add(:id,"First airtime must be filled out and in the ET timezone")
      false
    end
  end
end

app/models/tbl_spec.rb
class TblSpec < ActiveRecord::Base
	belongs_to :sheet

	def self.to_csv
    CSV.generate do |csv|
      csv << column_names[4..-1]
      all.each do |sheet|
        csv << sheet.attributes.values_at(*column_names[4..-1])
      end
    end
  end
end

app/models/teamname.rb
class Teamname < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :sheets

  validates_presence_of :name, on: :create
  validates_presence_of :email, on: :create
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to sheets_path
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
  

end

app/helpers/ae_specs_helper.rb
module AeSpecsHelper
end

app/helpers/airtimes_helper.rb
module AirtimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/helpers/tbl_specs_helper.rb
module TblSpecsHelper
end

app/helpers/teamnames_helper.rb
module TeamnamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="background-image:url('<%=asset_path 'carbonfibertile.png'%>')">
<head>
  <title>Bugpromo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Francois+One' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id = "topbar">
		<div id = "topbar_left">
      <ul class = "topbar_list">
        <p><%= link_to "PROMO MANAGER", sheets_path %></p>
  			<% if current_user %>
  	      <li><%= link_to "NEW DUB SHEET", new_sheet_path %></li>
          <li><%= link_to "MANAGE PROPERTIES", properties_path %></li>
          <li><%= link_to "MANAGE TEAMNAMES", teamnames_path %></li>
  			<% end %>
      </ul>
		</div>

		<div id = "topbar_right">
      <ul class = "topbar_list">
  		  <% if current_user %>
          <p>LOGGED IN AS <%= current_user.name.upcase %></p>
          <li><%= link_to "LOG OUT", session_path("current"), method: :delete %></li>
        <% else %>
          <li><%= link_to "LOG IN", new_session_path %></li>
          <li><%= link_to "SIGN UP", new_user_path %></li>
        <% end %>
      </ul>
		</div>
	</div>
  <div id="logo_crop">
    <%=image_tag("logo_snet.png")%>
  </div>

    <div id="main">
      <% if flash[:notice] %>
        <p id= "notice"><%= flash[:notice]%>
      <% end %>
      <% if flash[:alert] %>
        <p id= "error_explanation"><%= flash[:alert]%>
      <% end %>

      <%= yield %>

    </div>
  <div id="bottom_text">
    <a href="mailto:getreadydesign@gmail.com">© 2013 GETREADY DESIGN</a>
  </div>
</body>
</html>